### ISSUE TITLE
Consider exporting a cli "umbrella" interface

### ISSUE THREAD

**Issue by mutantcornholio** [paritytech/opstooling-js#13]
While considering pathways to https://github.com/paritytech/opstooling/issues/125, I realised that we probably will have more than one shared script between projects.  
WDYT on adding `bin` section to the package, with subcommands to later extension?  

I have something like this in mind: 
* File structure: 
```
/src
  /cli
    /commands
      generate-types.ts
      other-stuff.ts
    opstooling-scripts.ts
```
* `package.json`:
```
...
"bin": {
  "opstooling-scripts": "./dist/cli/opstooling-scripts.js"
},
...
```
* Usage (in the dependants):
```
npx opstolling-scripts --help
npx opstolling-scripts generate-types --schemas <path-to-schema-dir> --out <path-to-types-dir>
```

In terms of libraries, I'm a big fan of [commander](https://www.npmjs.com/package/commander) package, but anything aside from inventing it from scratch is fine by me.  

I'm also open to other approaches for the sharing scripts problem.  

cc/ @paritytech/opstooling

**Comment by joao-paulo-parity** [comment]
Fine by me

**Comment by koenw** [comment]
Fine with me too :)

**Comment by mutantcornholio** [comment]
Any opinions on compiling code on install vs. using `ts-node` on execution?

I personally prefer compiling, but `ts-node` seems to be more consistent with other configurations that we have.  

I think I'll start with `ts-node`, but that's easy enough to change at any moment, without breaking backwards-compatibility
