### ISSUE TITLE
Publish opstooling-js to npm registry

### ISSUE THREAD

**Issue by mutantcornholio** [paritytech/opstooling-js#31]
Currently we publish it to as a tag on git repo, which [forces](https://docs.npmjs.com/cli/v9/using-npm/scripts#life-cycle-scripts) devDeps installation as well as running `prepare` scripts.   

With the security questions around sorted out, let's publish the package to NPM registry.

**Comment by mordamax** [comment]
Related: https://github.com/paritytech/ci_cd/wiki/Publish-NPM-package-to-npmjs.com

From "[Security Discussion: NPM & Cargo](https://matrix.to/#/#Security-discussion:parity.io)"
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1177472/229585814-200bc131-bf90-4951-a988-a08fbf8aa675.png">

**Comment by mutantcornholio** [comment]
So, if nobody objects, I'm picking `@eng-automation/js` for this package (and `@eng-automation/integrations`, `@eng-automation/js-style`, ... for others)

**Comment by mutantcornholio** [comment]
https://github.com/paritytech/npm_publish_automation/pull/32

**Comment by mordamax** [comment]
```
npm ERR! 402 Payment Required - PUT https://registry.npmjs.org/@eng-automation%2fjs - You must sign up for private packages

npm ERR! A complete log of this run can be found in:
```

https://github.com/paritytech/npm_publish_automation/actions/runs/4620840626/jobs/8171506007

**Comment by mutantcornholio** [comment]
> ```
> npm ERR! 402 Payment Required - PUT https://registry.npmjs.org/@eng-automation%2fjs - You must sign up for private packages
> 
> npm ERR! A complete log of this run can be found in:
> ```
> 
> https://github.com/paritytech/npm_publish_automation/actions/runs/4620840626/jobs/8171506007

Yeah, this is still in progress

**Comment by alvicsam** [comment]
Guys, sorry I've missed the discussion. Is it possible to publish packages to `@parity` org? There is no strict requirement but I think it's better for naming consistency. So to have something like this:

 - parity/opstooling-js
 - parity/opstooling-integrations
 - parity/opstooling-testing

**Comment by mordamax** [comment]
@alvicsam please see our discussions in `Security Discussion: NPM & Cargo` -> and https://github.com/paritytech/npm_publish_automation/blob/main/packages.ts
There's no parity, each team can have their own name and that's ok
we scoped out team bundles under one name, and don't plan to create more

> Related: https://github.com/paritytech/ci_cd/wiki/Publish-NPM-package-to-npmjs.com
> 
> From "[Security Discussion: NPM & Cargo](https://matrix.to/#/#Security-discussion:parity.io)" <img alt="image" width="1021" src="https://user-images.githubusercontent.com/1177472/229585814-200bc131-bf90-4951-a988-a08fbf8aa675.png">

**Comment by alvicsam** [comment]
Okay, I see. Created @eng-automation org

**Comment by mutantcornholio** [comment]
All common packages have been published
https://www.npmjs.com/package/@eng-automation/js
https://www.npmjs.com/package/@eng-automation/js-style
https://www.npmjs.com/package/@eng-automation/integrations
https://www.npmjs.com/package/@eng-automation/testing
