### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by Bullrich** [paritytech/opstooling-js#45]
Currently, `opstooling-js` has a lot of utility methods that, unless you jump to read the code, are invisible. So it usually ends up with @mutantcornholio commenting in the code reviews that there is already a method for that. 

Let's write a clear and concise documentation showing a bit of each method and linking it to the file if necessary (or adding an example on how to use it). This would improve visibility and usability.

We can also use a doc generation tool using the documented methods.

**Comment by mutantcornholio** [comment]
> We can also use a doc generation tool using the documented methods.

Let's do this. Otherwise, keeping docs in check would be pain in the ass.
