### ISSUE TITLE
Modular packages

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/opstooling-js#5]
We should consider setting up workspaces so that we can publish more modular releases.

For instance, if we want to publish a `postgres`-related module, we could add a `opstooling-js/postgres` package to this repository instead of having to create a new repository for it.

See https://github.com/polkadot-js/apps/tree/23459132fbb9d3baab2bc6c5f7a8f8e4769395e7/packages for an example of how it could work.

**Comment by mordamax** [comment]
Won't do
